---
- name: Infrastructure Security - Firewall Management
  hosts: all
  become: yes

  tasks:

    - name: Validate firewall_action
      ansible.builtin.fail:
        msg: "firewall_action must be 'enable' or 'disable'"
      when: firewall_action is not defined

    ############################################################
    # REDHAT FAMILY (CentOS / RHEL / Oracle Linux)
    ############################################################

    - name: Enable Firewalld (RedHat)
      when:
        - firewall_action == "enable"
        - ansible_facts['os_family'] == "RedHat"
      block:

        - name: Install firewalld
          ansible.builtin.package:
            name: firewalld
            state: present

        - name: Start firewalld
          ansible.builtin.systemd:
            name: firewalld
            state: started
            enabled: yes

        - name: Allow services and ports
          ansible.posix.firewalld:
            service: "{{ item.svc | default(omit) }}"
            port: "{{ item.port | default(omit) }}"
            permanent: yes
            state: enabled
            immediate: yes
          loop:
            - { svc: 'http' }
            - { svc: 'ssh' }
            - { port: '10050/tcp' }

    - name: Disable Firewalld (RedHat)
      when:
        - firewall_action == "disable"
        - ansible_facts['os_family'] == "RedHat"
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no

    ############################################################
    # DEBIAN FAMILY (Ubuntu)
    ############################################################

    - name: Enable UFW (Ubuntu)
      when:
        - firewall_action == "enable"
        - ansible_facts['os_family'] == "Debian"
      block:

        - name: Install ufw
          ansible.builtin.package:
            name: ufw
            state: present

        - name: Allow HTTP
          community.general.ufw:
            rule: allow
            name: "Apache"

        - name: Allow SSH
          community.general.ufw:
            rule: allow
            name: "OpenSSH"

        - name: Allow Zabbix Port
          community.general.ufw:
            rule: allow
            port: "10050"
            proto: tcp

        - name: Enable UFW
          community.general.ufw:
            state: enabled

    - name: Disable UFW (Ubuntu)
      when:
        - firewall_action == "disable"
        - ansible_facts['os_family'] == "Debian"
      community.general.ufw:
        state: disabled
