---
- name: Infrastructure Security - Firewall Management
  hosts: all
  become: yes
  # ตัวแปร firewall_action จะถูกส่งมาจาก Survey ที่คุณตั้งค่าไว้

  tasks:
    # --- กรณีเลือก disable ---
    - name: Section - Disable Firewall
      when: firewall_action == "disable"
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no