---
- name: Infrastructure Security - Firewall Control Automation
  hosts: all
  become: yes
  vars:
    # รายการ Port และ Service
    allowed_services:
      - http
      - ssh
    allowed_ports:
      - 10050/tcp  # Zabbix Agent

  tasks:
    - name: 1. Install Python 3 if missing (Pre-requisite)
      ansible.builtin.raw: test -e /usr/bin/python3 || (yum install -y python3 || apt-get install -y python3)
      changed_when: false

    - name: 2. Ensure Firewalld is installed
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: 3. Ensure Firewalld is started and enabled
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: 4. Allow Standard Services (HTTP, SSH)
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ allowed_services }}"

    - name: 5. Allow Custom Ports (Zabbix 10050)
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ allowed_ports }}"

    - name: 6. Verify Firewall Rules
      ansible.builtin.command: firewall-cmd --list-all
      register: fw_status
      changed_when: false

    - name: 7. Show Firewall Status
      ansible.builtin.debug:
        var: fw_status.stdout_lines