---
- name: Infrastructure Security - Firewall Management
  hosts: all
  become: yes

  tasks:

    ############################################################
    # REDHAT FAMILY (CentOS / RHEL / Oracle Linux)
    ############################################################

    - name: Configure Firewalld (RedHat Family)
      when: ansible_facts['os_family'] == "RedHat"
      block:

        - name: Install firewalld
          ansible.builtin.package:
            name: firewalld
            state: present

        - name: Start and Enable firewalld
          ansible.builtin.systemd:
            name: firewalld
            state: started
            enabled: yes

        - name: Allow services and ports
          ansible.posix.firewalld:
            service: "{{ item.svc | default(omit) }}"
            port: "{{ item.port | default(omit) }}"
            permanent: yes
            state: enabled
            immediate: yes
          loop:
            - { svc: 'http' }
            - { svc: 'ssh' }
            - { port: '10050/tcp' }

    ############################################################
    # DEBIAN FAMILY (Ubuntu)
    ############################################################

    - name: Configure UFW (Debian Family)
      when: ansible_facts['os_family'] == "Debian"
      block:

        - name: Install ufw
          ansible.builtin.package:
            name: ufw
            state: present

        - name: Allow HTTP
          ansible.builtin.command: ufw allow http

        - name: Allow SSH
          ansible.builtin.command: ufw allow ssh

        - name: Allow Zabbix Port
          ansible.builtin.command: ufw allow 10050/tcp

        - name: Enable UFW
          ansible.builtin.command: ufw --force enable
