---
- name: Infrastructure Security - Disable Firewall
  hosts: all
  become: yes

  tasks:
    - name: Stop and Disable Firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Verify Firewall is stopped
      ansible.builtin.command: systemctl status firewalld
      register: fw_off_status
      ignore_errors: yes
      changed_when: false

    - name: Show Status
      ansible.builtin.debug:
        msg: "Firewall has been disabled on {{ inventory_hostname }}"